CREATE PROCEDURE addmahasiswa (@npm NVARCHAR(8), @nama NVARCHAR(50),
@tempat_lhr NVARCHAR(30), @tanggal_lhr DATE, @sex NVARCHAR(1), @thn_masuk
NVARCHAR(4), @idprodi INT, @idstatusaka INT)
AS
BEGIN
DECLARE @NPM_MHS int;
BEGIN TRY
BEGIN TRANSACTION
INSERT INTO MAHASISWA (npm, nama, tempat_lhr, tanggal_lhr, sex, thn_masuk,
idprodi, idstatusaka)
VALUES (@npm, @nama, @tempat_lhr, @tanggal_lhr, @sex, @thn_masuk, @idprodi,
@idstatusaka)
SAVE TRANSACTION POINT1
SELECT @NPM_MHS = COUNT(*) FROM MAHASISWA WHERE npm = @npm IF @NPM_MHS > 1
BEGIN
ROLLBACK TRANSACTION
PRINT 'NPM MAHASISWA SUDAH ADA YANG PUNYA'
SAVE TRANSACTION POINT2
END
ELSE
BEGIN
COMMIT TRANSACTION PRINT 'DATA MAHASISWA BERHASIL DITAMBAHKAN'
END
RETURN 0
END TRY
BEGIN CATCH
RAISERROR 13003 'KESALAHAN INPUT, SILAHKAN ULANGI LAGI'
IF @@TRANCOUNT > 0
ROLLBACK TRANSACTION POINT1
END CATCH
END
GO
GO


EXEC addmahasiswa '1775399', 'EGI MAULANA FIKRI', 'Medan', '1999-12-12', 'L', '2017', 6, 1
GO